# /etc/profile has the pathappend function in
# plus /etc/profile.d/xorg.sh has our x environment variables
# which is soruced by /etc/profile
source /etc/profile

cat > /usr/lib/libXau.la << "EOF"
# libXau.la - a libtool library file
# Generated by libtool (GNU libtool) 2.5.4
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libXau.so.6'

# Names of this library.
library_names='libXau.so.6.0.0 libXau.so.6 libXau.so'

# The name of the static archive.
old_library='libXau.a'

# Linker flags that cannot go in dependency_libs.
inherited_linker_flags=''

# Libraries that this one depends upon.
dependency_libs=''

# Names of additional weak libraries provided by this library
weak_library_names=''

# Version information for libXau.
current=6
age=0
revision=0

# Is this an already installed library?
installed=no

# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/usr/local/lib'
EOF



cat > /usr/lib/libXdmcp.la << "EOF"
# libXdmcp.la - a libtool library file
# Generated by libtool (GNU libtool) 2.4.7
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libXdmcp.so.6'

# Names of this library.
library_names='libXdmcp.so.6.0.0 libXdmcp.so.6 libXdmcp.so'

# The name of the static archive.
old_library='libXdmcp.a'

# Linker flags that cannot go in dependency_libs.
inherited_linker_flags=''

# Libraries that this one depends upon.
dependency_libs=''

# Names of additional weak libraries provided by this library
weak_library_names=''

# Version information for libXdmcp.
current=6
age=0
revision=0

# Is this an already installed library?
installed=no

# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='/usr/local/lib'
EOF



#./autogen.sh --prefix=/usr
./configure $XORG_CONFIG
make

make install

rm -vf /usr/lib/libXdmcp.la
rm -vf /usr/lib/libXau.la 